#' ============================================================================
#' Pseudobulk Aggregation and DESeq2 Differential Expression
#' ============================================================================
#'
#' Manuscript: Multi-omics Reveals How Diet and Exercise Improve Peripheral Neuropathy
#' Authors:    Eid SA, Guo K, Noureldein MH, Jang D-G, Allouch AM, Miller CM, Kiriluk CP,
#   Lentz W, Boutary S, Mule JJ, Pennathur S, Bhatt DK, Feldman EL, Hur J
#'
#' Contact:
#   Dr. Kai Guo        <guokai8@gmail.com>
#   Dr. Junguk Hur     <junguk.hur@med.UND.edu>
#'
#' Description:
#'   Aggregates single-cell counts per sample and cell type into pseudobulk matrices.
#   Filters low-count genes (>60 total counts) and runs DESeq2 for pairwise
#   comparisons (HFD vs SD, DR vs HFD, EX vs HFD, DREX vs HFD).
#'
#' Input:
#'   pseudo_bulk_data.csv, single_cell_sample_metadata.csv
#'
#' Output:
#'   sc_integration_predata.rdata, DESeq2 result CSVs per cell type (p < 0.01)
#'
#' Related figures:
#'   Used as input for integration analyses (Fig. 5, Fig. 7)
#'
#' ============================================================================
# ==============================================================================
# Pseudo-bulk RNA-seq Analysis Using DESeq2
# Methods: "pseudo-bulk RNA-seq profiles were generated from single-cell counts 
#          and analyzed using DESeq2 (v1.38.3)"
# ==============================================================================

setwd("Desktop/Project/Step/")

# ------------------------------------------------------------------------------
# 1. Load Pseudo-bulk Data and Metadata
# Methods: "Pseudobulk scRNA-seq profiles for each experimental condition 
#          were generated by aggregating single-cell count data by sample 
#          and cell type"
# ------------------------------------------------------------------------------
d <- read.csv("pseudo_bulk_data.csv", row.names=1)
group <- read.csv("single cell_sample_metadata.csv", row.names=1)

# Standardize sample IDs
group$Sample_ID <- sub('.*M', 'M', sub('\\-', '', group$Sample_ID))
rownames(group) <- group$Sample_ID

library(DESeq2)

# ------------------------------------------------------------------------------
# 2. DESeq2 Analysis Function for Each Cell Type
# Methods: "genes with at least 60 total counts were retained, conducting 
#          differential expression analysis using DESeq2"
# ------------------------------------------------------------------------------
getdds <- function(d, group, celltype){
  cat(celltype, "\n")
  
  # Extract columns for specific cell type
  sampleid <- grep(celltype, colnames(d), value=T)
  dd <- d[, sampleid]
  
  # Convert to integer counts (required by DESeq2)
  dd[] <- lapply(dd, as.integer)
  
  # Extract condition information from sample names
  condition <- group[sub('_.*', '', sampleid), "Condition"]
  
  # Create DESeq2 dataset
  dds <- DESeqDataSetFromMatrix(dd, DataFrame(condition), ~condition)
  
  # Filter low-count genes (at least 60 total counts across samples)
  keep <- rowSums(counts(dds)) >= 60
  dds <- dds[keep, ]
  
  # Return NULL if no genes pass filter
  if(sum(keep) == 0) return(NULL)
  
  # Run DESeq2 differential expression analysis
  dds <- DESeq(dds)
  return(dds)
}

# ------------------------------------------------------------------------------
# 3. Run DESeq2 for All Cell Types
# ------------------------------------------------------------------------------
celltype <- unique(sub('.*_', '', colnames(d)))
celltype <- setdiff(celltype, "SC3")  # Exclude SC3 if necessary

# Run DESeq2 for each cell type
dds <- lapply(celltype, function(x) getdds(d, group, celltype=x))
names(dds) <- celltype

# ------------------------------------------------------------------------------
# 4. Extract DEGs for All Pairwise Comparisons
# Methods: "genes retained for downstream analyses based on an unadjusted 
#          p-value<0.01"
# ------------------------------------------------------------------------------
getDEG <- function(dds){
  # Get group levels from design factor
  group_levels <- levels(colData(dds)$condition)
  
  # Generate all pairwise combinations
  comparisons <- combn(group_levels, 2, simplify=FALSE)
  
  # Extract results for each pair
  all_results <- setNames(
    lapply(comparisons, function(comp) {
      results(dds, contrast=c("condition", comp[1], comp[2]))
    }),
    sapply(comparisons, paste, collapse="_vs_")
  )
  return(all_results)
}

# Get differential expression results for all cell types
deg <- lapply(dds, function(x) getDEG(x))

# Extract significant genes (p-value < 0.01)
degs <- lapply(deg, function(x) 
  lapply(x, function(y) rownames(subset(y, pvalue < 0.01))))

# Get unique gene list for each cell type
genes <- lapply(degs, function(x) unique(unlist(x)))

# ------------------------------------------------------------------------------
# 5. Prepare Data for Integration
# Calculate mean expression per group for integration analysis
# ------------------------------------------------------------------------------
dm <- d %>%
  rownames_to_column(var="gene") %>%
  gather(sam, val, -gene) %>%
  separate(sam, c("sam", "cell"), sep="_") %>%
  mutate(Group=group[sam, "Condition"]) %>%
  group_by(Group, cell, gene) %>%
  summarise(mu=mean(val))

# Split by cell type
dx <- split(dm[, c(1, 3, 4)], dm$cell)

# Convert to wide format
dx <- lapply(dx, function(x) 
  x %>% spread(Group, mu) %>% column_to_rownames(var="gene"))

# Remove genes with zero expression across all groups
dx <- lapply(dx, function(x) x[rowSums(x) > 0, ])

# ------------------------------------------------------------------------------
# 6. Prepare Final Integration Dataset
# Extract DEGs for each cell type
# ------------------------------------------------------------------------------
predata <- function(celltype){
  g <- genes[[celltype]]
  p <- dx[[celltype]]
  return(p[g, ])
}

scd <- lapply(names(genes), function(x) predata(x))
names(scd) <- names(genes)

# Save pre-processed data for integration
save(scd, file="sc_integration_predata.rdata")
